# Generated by Django 2.0.10 on 2020-11-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impulseresponse',
            old_name='impulse_response',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='loop',
            old_name='loop',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='sound',
            old_name='sound',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='wavetable',
            old_name='wavetable',
            new_name='file',
        ),
        migrations.AddField(
            model_name='loop',
            name='bpm',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loop',
            name='key',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sound',
            name='key',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
