# Generated by Django 2.0.10 on 2020-11-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_create_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundkit',
            name='sound_key_code',
        ),
        migrations.AddField(
            model_name='soundkit',
            name='sound_key_codes',
            field=models.ManyToManyField(to='sounds.SoundKeyCode'),
        ),
    ]
