# Generated by Django 2.0.10 on 2020-11-12 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0003_auto_20201107_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyKeyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=20)),
                ('key_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.KeyCode')),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frequency_key_codes', models.ManyToManyField(to='sounds.FrequencyKeyCode')),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.Sound')),
            ],
        ),
    ]
