# Generated by Django 2.0.10 on 2020-11-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_auto_20201113_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencykit',
            name='sound',
        ),
    ]
